name: HiPlugin
version: 3.4-Alpha
main: top.whitecola.HiPlugin
author: [White_cola,Chloe030120]
#commands:
#  hip:
#    usage: /hip <commands> [args] ...
#permissions:
#  hiplugin.sayhi:
#    default: op
#  hiplugin.example:
#    default: op